### PR TITLE
remove duplicate nodes

### LINKED ISSUE #130: Statistics service - duplicated nodes (same host/IP) with different public key
In the statistics service, we have duplicated nodes with the same domain and different public keys.
For example:

```
{
   "peerStatus":{
      "isAvailable":true,
      "lastStatusCheck":1642429201521
   },
   "apiStatus":{
      "restGatewayUrl":"https://7.dusan.gq:3001",
      "isAvailable":true,
      "isHttpsEnabled":true,
      "lastStatusCheck":1642429202077,
      "webSocket":{
         "isAvailable":true,
         "wss":true,
         "url":"wss://7.dusan.gq:3001/ws"
      },
      "nodePublicKey":"D70CC540DB83B732EC3CED496C399914BF5C8A17DB05D11CE3871ACF2D308301",
      "chainHeight":100580,
      "finalization":{
         "height":100560,
         "epoch":141,
         "point":37,
         "hash":"72B9934413FE7AE27B24DE46C41A282610A875D9CA9B6E559CFEE74A4E4CE346"
      },
      "nodeStatus":{
         "apiNode":"up",
         "db":"up"
      },
      "restVersion":"2.4.0"
   },
   "_id":"61e57b3488fe3f00128a19bf",
   "version":16777985,
   "publicKey":"F099AB5ADF1920E7EC227004EA829C88EEA4955033914653D4F203EF9578A40B",
   "networkGenerationHashSeed":"7FCCD304802016BEBBCD342A332F91FF1F3BB5E902988B352697BE245F48E836",
   "roles":7,
   "port":7900,
   "networkIdentifier":152,
   "host":"7.dusan.gq",
   "friendlyName":"dusanjp7",
   "lastAvailable":"2022-01-17T14:20:36.488Z",
   "hostDetail":{
      "host":"7.dusan.gq",
      "coordinates":{
         "latitude":47.6034,
         "longitude":-122.3414
      },
      "location":"Seattle, WA, United States",
      "ip":"66.94.127.200",
      "organization":"Contabo Inc",
      "as":"AS40021 Contabo Inc.",
      "continent":"North America",
      "country":"United States",
      "region":"WA",
      "city":"Seattle",
      "district":"",
      "zip":"98111"
   },
   "__v":0
}
```

```
{
   "_id":"61e57b3488fe3f00128a19d2",
   "version":16777985,
   "publicKey":"0DB68D406B4799F74190297BE4BA872721ADFA04FE6A330AA0E667B2BCAD21FA",
   "networkGenerationHashSeed":"7FCCD304802016BEBBCD342A332F91FF1F3BB5E902988B352697BE245F48E836",
   "roles":3,
   "port":7900,
   "networkIdentifier":152,
   "host":"7.dusan.gq",
   "friendlyName":"dusanjp7",
   "lastAvailable":"2022-01-17T14:20:01.359Z",
   "__v":0
}
```

Steps to reproduce:
- spin node for given host
- stop node, reset data (keys)
- start new node on same host 

Result:
Some nodes in `/node/peers` returns still old public key. It's easier to reproduce on testnet.

Expected result:
Statistics services should remove such duplicates and detect that a second entry (with the wrong key) should be removed.

### PR DESCRIPTION
**Pull request by yilmazbahadir**
fixes #130 and merges `main` branch changes back to `dev`(post-release operation)

### What's the fix?
duplicate nodes and nodes from the wrong networks are removed.

### CODE REVIEW

File: src/services/NodeMonitor.ts [hunk 1]
```diff
@@ -204,6 +204,14 @@ export class NodeMonitor {
 				const nodeStatus = await ApiNodeService.getNodeInfo(hostUrl);
 
 				if (nodeStatus) {
+					// if the values we got is different than the node/info then remove the node from the list
```
Comment (0x6861746366574) [inline src/services/NodeMonitor.ts:207]: Note grammar: is > are

**Review by 0x6861746366574 — APPROVED** [review]

File: src/services/NodeMonitor.ts (hunk 1 above)
Comment (yilmazbahadir) [reply src/services/NodeMonitor.ts]: Fixed

**Review by cryptoBeliever — APPROVED** [review]
